import Head from 'next/head';

import { IPostData } from '@/services/PostService';

interface IProps {
  selectedPost: IPostData[];
}

export default function ArtifactCard({ selectedPost }: IProps) {
  return (
    <div>
      <Head>
        <title>{selectedPost[0].title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
