import Head from 'next/head';

import { PostData } from '@/services/PostService';

interface Props {
  selectedPost: PostData[];
}

const SideDrawer: React.FC<Props> = ({ selectedPost }: Props) => {
  return (
    <div>
      <Head>
        <title>{selectedPost[0].title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default SideDrawer;
