import { Container, Flex, Text } from '@chakra-ui/react';
import { GetServerSideProps } from 'next';
import Head from 'next/head';
import { Inter } from 'next/font/google';

import UserService, { UserData } from '@/services/UserService';
import styles from '@/pages/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

interface Props {
  users: UserData[];
}

export default function Users({ users }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Text fontWeight={'bold'}>Users</Text>
        {users.map((user: UserData) => (
          <Container key={user.userId}>
            <Flex
              textAlign={'left'}
              alignItems={'center'}
              justifyContent={'space-between'}
            >
              <Text>{user.name}</Text>
            </Flex>
          </Container>
        ))}
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  const users = await UserService.getAll();

  return {
    props: {
      users,
    },
  };
};
